site_name: BayBE
site_url: https://emdgroup.github.io/baybe/
repo_url: https://github.com/emdgroup/baybe/
theme:
  name: material
  logo: assets/favicon.ico
  palette:
    scheme: slate
    primary: custom
    accent: custom

extra_css:
  - stylesheets/extra.css