site_name: BayBE
site_url: https://emdgroup.github.io/baybe/
repo_url: https://github.com/emdgroup/baybe/
copyright: Copyright &copy; 2022-2025 Merck KGaA, Darmstadt, Germany
theme:
  name: material
  logo: assets/favicon.ico
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

extra_css:
  - stylesheets/extra.css

nav:
  - Readme: README.md
  - Concepts:
    - Serialization: userguide/serialization.md
  - API Reference: reference/  

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.superfences
  - toc:
      permalink: "#"

plugins:
- search  
- gen-files:
    scripts:
    - docs/scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - griffe_fieldz
        import:
        - https://pandas.pydata.org/docs/objects.inv

extra:
  toc:
    disable:
      - README.md
  navigation:
    disable:
      - README.md