site_name: BayBE
site_url: https://emdgroup.github.io/baybe/
repo_url: https://github.com/emdgroup/baybe/
theme:
  name: material
  logo: assets/favicon.ico
  palette:
    scheme: slate
    primary: custom
    accent: custom

extra_css:
  - stylesheets/extra.css

nav:
  - Concepts:
    - userguide/serialization.md
  - API Reference: reference/  

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- search  
- gen-files:
    scripts:
    - docs/scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings
