[pytest]
strict = true

markers =
    filterwarnings: Apply warning filters to a test

addopts = 
    --doctest-modules 
    --ignore=examples
    --ignore=docs
    
    ; Avoids import errors due to optional dependencies
    --doctest-ignore-import-errors  

testpaths = 
    baybe
    tests

filterwarnings =
    ; Treat warnings as errors
    error

    ; Temporary ignores
    ; -----------------
    ; Torch JIT deprecation warning triggered during linear_operator import
    ignore:.*torch.jit.script.*:DeprecationWarning
    ; Invalid escape sequence in pyro.ops.stats docstring
    ; Fixed upstream but unreleased: https://github.com/pyro-ppl/pyro/issues/3450
    ignore:.*invalid escape sequence.*:SyntaxWarning
    ignore:.*invalid escape sequence.*:DeprecationWarning
    ; https://github.com/meta-pytorch/botorch/pull/3279
    ignore:chol argument to CholLinearOperator should be a TriangularLinearOperator.*:DeprecationWarning:linear_operator.operators.chol_linear_operator
    ; Needs proper fix for pandas 3.0 compatibility
    ignore:Setting an item of incompatible dtype is deprecated:FutureWarning:baybe.constraints.discrete
    ; https://github.com/shap/shap/issues/4280 (fixed in shap>=0.51.0, but only available for Python 3.11+)
    ignore:Conversion of an array with ndim > 0 to a scalar is deprecated:DeprecationWarning:shap.explainers.other._maple
    ; https://github.com/cornellius-gp/linear_operator/issues/131
    ignore:Sparse invariant checks are implicitly disabled.*:UserWarning:linear_operator

    ; Numerics/optimization
    ; ---------------------
    ignore:.*add(ed|ing) jitter.*:linear_operator.utils.warnings.NumericalWarning
    ignore:Negative variance values detected.*:linear_operator.utils.warnings.NumericalWarning
    ignore:Optimization failed.*:RuntimeWarning:botorch.optim.optimize
    ; Note: File format instead of module format needed due to BoTorch reraising using `warn_explicit` without `module` argument
    ignore:`scipy_minimize` terminated with status .*:botorch.exceptions.warnings.OptimizationWarning:.*botorch/fit
    ; BoTorch warning recommending to switch to log-versions of acquisition functions
    ignore:.*has known numerical issues that lead to suboptimal optimization performance.*:botorch.exceptions.warnings.NumericsWarning:botorch.acquisition
    
