[pytest]
addopts = 
    --doctest-modules 
    --ignore=examples
    --ignore=docs
    
    ; Avoids import errors due to optional dependencies
    --doctest-ignore-import-errors  

testpaths = 
    baybe
    tests

xfail_strict=true

filterwarnings =
    error
    ; Numerics/optimization
    ignore:A not p.d., added jitter of .*:linear_operator.utils.warnings.NumericalWarning
    ignore:Optimization failed.*:RuntimeWarning:botorch.optim.optimize
