"""Candidates module for managing the lazy candidate generation."""

from typing import Protocol

import narwhals as nw
from attr.validators import deep_iterable, instance_of, min_len
from attrs import define, field
from typing_extensions import override

from baybe.constraints import DISCRETE_CONSTRAINTS_FILTERING_ORDER, validate_constraints
from baybe.constraints.base import DiscreteConstraint
from baybe.exceptions import InfiniteSpaceError
from baybe.parameters.base import DiscreteParameter
from baybe.searchspace.utils import build_constrained_product
from baybe.utils.basic import to_tuple
from baybe.utils.dataframe import to_lazy_narwhals
from baybe.utils.validation import validate_parameter_input


class CandidatesProtocol(Protocol):
    """Type protocol specifying the interface for Candidates to implement."""

    parameters: tuple[DiscreteParameter, ...] = field(
        converter=to_tuple,
        validator=[
            min_len(1),
            deep_iterable(
                member_validator=instance_of(DiscreteParameter),
            ),
        ],
    )
    """
    The parameters that define the search space for which candidates are generated.
    """

    @property
    def is_finite(self) -> bool:
        """Define whether the candidate set is finite or infinite.

        Returns:
            Whether the candidate set is finite.
        """

    def to_lazy_candidates(self) -> nw.LazyFrame:
        """Generate the candidates from the given parameters and constraints.

        Returns:
            The candidates as a lazy dataframe.
        """


@define(frozen=True)
class ProductCandidates(CandidatesProtocol):
    """Class for managing product candidates.

    The candidates are generated by calculating the cartesian product of the parameter
    values and applying constraints if available.
    """

    parameters: tuple[DiscreteParameter, ...] = field(
        converter=to_tuple,
        validator=[
            min_len(1),
            deep_iterable(
                member_validator=instance_of(DiscreteParameter),
            ),
        ],
    )

    constraints: tuple[DiscreteConstraint, ...] = field(
        converter=lambda x: (
            to_tuple(
                sorted(
                    x,
                    key=lambda c: DISCRETE_CONSTRAINTS_FILTERING_ORDER.index(
                        c.__class__
                    ),
                )
            )
            if x is not None
            else ()
        ),
        factory=tuple,
        validator=deep_iterable(
            member_validator=instance_of(DiscreteConstraint),
        ),
    )
    """The constraints to apply to the cartesian product of the parameter values."""

    @override
    @property
    def is_finite(self) -> bool:
        # TODO: Need a property for each DiscreteParameter to check if it's finite then
        #   replace here with: return all(p.is_finite for p in self.parameters)
        return True

    @override
    def to_lazy_candidates(self) -> nw.LazyFrame:
        """Create a lazy data frame to represent candidates.

        Calculate the cartesian product of the parameter values and apply the
        constraints.

        Raises:
            InfiniteSpaceError: If the search space is infinite.

        Returns:
            The finite set of candidates as a lazy dataframe.
        """
        if not self.is_finite:
            raise InfiniteSpaceError(
                "Cannot create candidates for an infinite search space."
            )

        if len(self.constraints) >= 1:
            validate_constraints(self.constraints, self.parameters)

        candidates_df = build_constrained_product(self.parameters, self.constraints)
        # TODO: Remove to lazy once build_constrained_product returns a nw.LazyFrame
        return to_lazy_narwhals(candidates_df)


@define(frozen=True)
class TableCandidates(CandidatesProtocol):
    """Class for managing candidates provided as a table directly."""

    parameters: tuple[DiscreteParameter, ...] = field(
        converter=to_tuple,
        validator=[
            min_len(1),
            deep_iterable(
                member_validator=instance_of(DiscreteParameter),
            ),
        ],
    )

    dataframe: nw.LazyFrame = field(
        validator=instance_of(nw.LazyFrame),
        converter=to_lazy_narwhals,
    )
    """The dataframe containing the candidates."""

    def __attrs_post_init__(self):
        # TODO: Remove .collect().to_pandas() once we supports validation on lazy frames
        validate_parameter_input(self.dataframe.collect().to_pandas(), self.parameters)

    @override
    @property
    def is_finite(self) -> bool:
        return True

    @override
    def to_lazy_candidates(self) -> nw.LazyFrame:
        """Return the candidates as a lazy dataframe.

        Returns:
            The finite set of candidates as a lazy dataframe.
        """
        return self.dataframe
