name: 'Create Issue Reminder'

permissions: {}

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Required for create-reminder-action to post issue comments

    steps:
      - name: check for reminder
        uses: agrc/create-reminder-action@c2025868f56a49dfc239012c78cb8e2beee5554e # v1